// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_ATOI_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_ATOI_H

int atoi(char *s);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_ATOI_H
