// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H

void* malloc(size_t nbytes);
void free(void *aptr);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
