// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_RAND_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_RAND_H

void srand(unsigned int seed);
int rand();

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_RAND_H
