// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H

int fflush(FILE *fp);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H
