// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H

int __swsetup(FILE *fp);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H
