// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_FMOD_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_FMOD_H


float __ieee754_fmodf(float x, float y);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_FMOD_H
