// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H

typedef int __int32_t;

__int32_t __ieee754_rem_pio2f(float x, float *y);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H
