// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_SQRT_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_SQRT_H


float __ieee754_sqrtf(float x);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_SQRT_H
