// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_TAN_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_TAN_H


float __kernel_tanf(float x, float y, int iy);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_TAN_H
