// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_ISNAN_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_ISNAN_H

int isnan(double x);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_ISNAN_H
