// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H


float floorf(float x);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H
