// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H

float fabsf(float x);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H
