// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_FMOD_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_FMOD_H

float fmodf(float x, float y);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_FMOD_H
