// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H

float copysignf(float x, float y);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
