// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H


float scalbnf(float x, int n);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
