// STATUS: NOT STARTED

#ifndef M_NAGAURA_REIKOKU_SRC_INGAME_MAP_DOOR_CONTE_H
#define M_NAGAURA_REIKOKU_SRC_INGAME_MAP_DOOR_CONTE_H


void DoorOpenConteInit();
u_char DoorOpenConte();

#endif // M_NAGAURA_REIKOKU_SRC_INGAME_MAP_DOOR_CONTE_H
