// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_INDEX_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_INDEX_H

char* index(char *s, int c);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_INDEX_H
