// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H

int* __errno();

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H
