// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H

int _close_r(_reent *ptr, int fd);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H
