// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H

extern _reent *_impure_ptr;


#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
