// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H

extern char _ctype_[257];


#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
