// STATUS: NOT STARTED

#ifndef LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_TOLOWER_H
#define LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_TOLOWER_H

int tolower(int c);

#endif // LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_TOLOWER_H
