// STATUS: NOT STARTED

#ifndef M_NAGAURA_REIKOKU_SRC_OS_EEIOP_ADPCM_EA_MAP_H
#define M_NAGAURA_REIKOKU_SRC_OS_EEIOP_ADPCM_EA_MAP_H

void EAdpcmMapMain();

#endif // M_NAGAURA_REIKOKU_SRC_OS_EEIOP_ADPCM_EA_MAP_H
