// STATUS: NOT STARTED

#ifndef M_NAGAURA_REIKOKU_SRC_GRAPHICS_GRAPH2D_SNAPSHOT_H
#define M_NAGAURA_REIKOKU_SRC_GRAPHICS_GRAPH2D_SNAPSHOT_H


void TakeSnapshot(char *data_i, char *data_o, int size_w, int size_h, int type);

#endif // M_NAGAURA_REIKOKU_SRC_GRAPHICS_GRAPH2D_SNAPSHOT_H
