// STATUS: NOT STARTED

#ifndef M_NAGAURA_REIKOKU_SRC_INGAME_MAP_FURN_SPE_FSPE_ACS_H
#define M_NAGAURA_REIKOKU_SRC_INGAME_MAP_FURN_SPE_FSPE_ACS_H

void FSpeMapDataMapping();
u_char* FSpeGetTopAddr(u_short fact_no);

#endif // M_NAGAURA_REIKOKU_SRC_INGAME_MAP_FURN_SPE_FSPE_ACS_H
